### ISSUE TITLE
Task Methods Should Take CancellationToken instead of CancellationTokenSource

### ISSUE THREAD

**Issue by Lukazoid** [akarnokd/Reactive4.NET#1]
The methods `FirstTask`, `LastTask` and `IgnoreElementsTask` all take a `CancellationTokenSource` which I feel is unneccessary and isn't consistent with other task returning async methods in .NET.

If I wish to subscribe to a stream and get the last item, knowing I can never be cancelled, currently this has to look like the following:

    T lastItem;
    using(var cts = new CancellationTokenSource())
    {
        lastItem = await stream.LastTask(cts).ConfigureAwait(false);
    }

If these methods instead took a `CancellationToken` it could look like so:

    var lastItem = await stream.LastTask(CancellationToken.None).ConfigureAwait(false);

If there is a prerequisite that these `Task` methods need to cancel themselves (I don't believe this is the case), they could create their own internal `CancellationTokenSource` via `CancellationTokenSource.CreateLinkedTokenSource`. The resulting `Task` contains enough information for the caller to know whether it was cancelled (via a thrown OperationCanceledException).

**Comment by akarnokd** [comment]
I'm not that familiar with the whole CancellationToken approach as there is nothing like it in Java.

I guess overloads can be specified and the underlying infrastructure adjusted to work with the tokens.

Would you like to submit a PR?

**Comment by Lukazoid** [comment]
I will try and get a PR submitted shortly.

Would you prefer if I left the current methods there (eliminate any breaking changes) and simply add overloads which take `CancellationToken`?

**Comment by akarnokd** [comment]
Yes, please add overloads.
