### ISSUE TITLE
Flattening operators wait for the entire source before propagating exception

### ISSUE THREAD

**Issue by Lukazoid** [akarnokd/Reactive4.NET#12]
With System.Reactive the following example completes almost immediately with the error:

	await Observable.Range(0, 100)
        .Select(x =>
        {
            if (x == 0)
            {
                return Observable.Throw<int>(new InvalidOperationException());
            }
            else
            {
                return Observable.Return(1).Delay(TimeSpan.FromSeconds(1));
            }
        })
        .Merge(10)
        .ToList()
        .ToTask(CancellationToken.None);

With this library the following example waits for all of the sequences to complete (> 10 seconds) before returning the error:

	await Flowable.Range(0, 100)
        .Map(x =>
        {
            if (x == 0)
            {
                return Flowable.Error<int>(new InvalidOperationException());
            }
            else
            {
                return Flowable.Just(1).Delay(TimeSpan.FromSeconds(1));
            }
        })
        .Merge(10)
        .ToList()
        .LastTask(CancellationToken.None);

Should these not both behave in a similar fashion? How can I make the Reactive4.NET operators behave more like the the operators from Rx?

**Comment by akarnokd** [comment]
This FlatMap delays errors until all sources terminate by design. It would be possible extend it to not wait, but it gets complicated.

**Comment by Lukazoid** [comment]
So the Reactive4 `Merge` operator is more equivalent to `MergeDelayError` from Rx?

**Comment by akarnokd** [comment]
Yes.

**Comment by Lukazoid** [comment]
Okay, I'll need to write something to be more like the Rx `Merge` operator then, my source takes hours before completion, if I manage it would you be interested in a PR?

**Comment by akarnokd** [comment]
Sure.

**Comment by Lukazoid** [comment]
If I simply cancelled the upstream and inner subscriptions in `OnError` what additional complications would I be missing?

**Comment by akarnokd** [comment]
You'd have to skip any queued items and perform an early cleanup.

**Comment by Lukazoid** [comment]
Thanks, I think that should be very similar to what `Cancel` does on the outer subscription except I don't want to set the `cancelled` flag.

Would you prefer this new mode of operation to use additional overloads of `FlatMap`/`Merge` with an `eagerError` parameter (false for existing overloads) or completely new methods like `FlagMapEagerError`/`MergeEagerError`?

**Comment by akarnokd** [comment]
The convention in RxJava is to have a `delayError` parameter or a `DelayError` postfix.

**Comment by Lukazoid** [comment]
Renaming the existing methods to have a `DelayError` suffix would be a breaking change (the new methods wouldn't have the suffix but they'd change the behaviour for existing users), so shall I add a `delayError` parameter instead for which the existing methods use `true`?

**Comment by akarnokd** [comment]
Sure.
