### ISSUE TITLE
GroupBy combined with FlatMap returning error is really slow

### ISSUE THREAD

**Issue by Lukazoid** [akarnokd/Reactive4.NET#14]
For me the following example always times out:

    Flowable.Range(0, 1000)
        .GroupBy(x => x % 2)
        .FlatMap(x => Flowable.Error<int>(new Exception()))
        .Test()
        .AwaitDone(TimeSpan.FromSeconds(10))
        .AssertValueCount(0)
        .AssertError(typeof(Exception));

As this is only 1000 items I'd expect it to complete in a lot less than 10 seconds.

**Comment by Lukazoid** [comment]
Maybe this is a full deadlock actually, because each group needs to progress to allow the entire `GroupBy` operator to complete? If that's the case I believe I definitely need #12

**Comment by akarnokd** [comment]
You should not ignore groups and since the default FlatMap delays errors, it will stop requesting more data and thus the sequence never completes.

**Comment by Lukazoid** [comment]
In my real use-case I am using the group and doing an operation on each item, but that operation is throwing an error, more like:

    .FlatMap(g => g.Map(x => SomeMethodWhichThrows(x)))

If I put this in the above example I still get the deadlock even though I am subscribing to the queue.

I think I can see what should be happening, each group subscription should be getting cancelled causing the group to be removed and a new group (with the same key) to be published, eventually every item should be seen and throw this exception, eventually the final stream should terminate.

I believe the problem is in `GroupedFlowable.DrainNormal`. Because the call `a.OnNext(v)` is resulting in cancellation of the subscription `DrainNormal` checks the `cancelled` flag and returns before requesting any more data from the upstream even though some items have been published and there will be more room available in the next group (with the same key).

If I'm on the right track I am happy to have a go at fixing this.

Perhaps every time a group is published we should be requesting `bufferSize` items from the upstream, as we have space in the new group?

**Comment by akarnokd** [comment]
Sure.
