### ISSUE TITLE
FlatMap style operators build exceptions which overflow the stack

### ISSUE THREAD

**Issue by Lukazoid** [akarnokd/Reactive4.NET#26]
The following example takes me ~35 seconds to run, the majority of the time is spent in `AggregateException.ToString()`:

```
async Task Main()
{
    var sw = Stopwatch.StartNew();
    try
    {
        await Flowable.Range(0, 1000)
        .FlatMap(x =>
        {
            return Flowable.Error<int>(() => new Exception($"Exception on item {x}"));
        })
        .ToList()
        .FirstTask(CancellationToken.None);
    }
    catch (Exception ex)
    {
        sw.Elapsed.Dump("Got exception");
        var exceptionMessage = ex.ToString();
        sw.Elapsed.Dump("Got exception message");
    }
}
```

If the number of items is much bigger we eventually end up with a `StackOverflowException` in `AggregateException.ToString()`.

I think this is because `ExceptionHelper.AddException` creates a more and more nested `AggregateException` for every exception which occurs. I believe it should actually detect it is already an `AggregateException` and create a new one with all the inner exceptions of the existing one plus the new exception, perhaps something like this:

```
internal static bool AddException(ref Exception error, Exception next)
{
    Exception comparand;
    Exception exception;
    do
    {
        comparand = Volatile.Read<Exception>(ref error);
        if (comparand == ExceptionHelper.Terminated)
            return false;
        exception = comparand switch
        {
            AggregateException aggr => new AggregateException(aggr.InnerExceptions.Concat(new[] { next })),
            { } existing => new AggregateException(new[] { existing, next }),
            null => next,
        };
    }
    while (Interlocked.CompareExchange<Exception>(ref error, exception, comparand) != comparand);
    return true;
}
```

Or alternatively in the existing code add a call to `.Flatten()` on the `new AggregateException`.

If this seems agreeable to you I will make a pull request.

Thanks for a great library, I love the backpressure aware manner 👍

**Comment by akarnokd** [comment]
Sounds good!
