### ISSUE TITLE
ConcatMapEager Can Deadlock for Synchronous Publishers

### ISSUE THREAD

**Issue by Lukazoid** [akarnokd/Reactive4.NET#3]
When using `ConcatMapEager`, if the mapping function returns a synchronous publisher, e.g. `Flowable.Just` or `Flowable.Range` it seems to get deadlocked when the maximum concurrency is less than the number of source elements. 

See the following examples (with maxConcurrency of 1 less than the number of elements):

    var result = Flowable.Range(0, 3)
        .ConcatMapEager(x =>
        {
            return Flowable.Just(x);
        }, 2);

    int last;
    var gotLast = result.BlockingLast(out last);

Or even this example which just has a large number of elements (more than the default maxConcurrency option):

    var result = Flowable.Range(0, Flowable.BufferSize() + 1)
        .ConcatMapEager(x =>
        {
            return Flowable.Just(x);
        });
    
    int last;
    var gotLast = result.BlockingLast(out last);

I am aware it is possible to work around this by deferring the subscription of the inner publisher by using `.SubscribeOn(Executors.Task)`. If this is expected and the preferred solution, feel free to close the issue.

**Comment by akarnokd** [comment]
Thanks, it is related to sync fusion with Just. I'll post a fix shortly.

**Comment by akarnokd** [comment]
Fixed via https://github.com/akarnokd/Reactive4.NET/commit/d9d51f760e21cbf72eaf62bd33bd39a333e7fd91

**Comment by Lukazoid** [comment]
Thanks for the quick reply and fix :) 

Could this also have explained why some elements from the mapped result were also going missing when `maxConcurrency` was less than the number of elements?

The following was only resulting in 8 mapped elements `0, 1, 2, 5, 6, 7, 8, 9`, 3 and 4 were missing:

    var result = Flowable.Range(0, 10)
        .ConcatMapEager(x =>
        {
            return Flowable.Just(x)
                .SubscribeOn(Executors.Task);
        }, 3);

If not, I'm happy to file a separate issue for this.

**Comment by akarnokd** [comment]
No, because SubscribeOn breaks fusion. It looks like a separate bug.

**Comment by akarnokd** [comment]
Fix for the latter in https://github.com/akarnokd/Reactive4.NET/commit/43d0bce1e6cd0b52e4b38da2de476bfa7e1fb461

**Comment by Lukazoid** [comment]
That's brilliant @akarnokd, do you think you'll be making a NuGet release with these fixes?

**Comment by akarnokd** [comment]
Sure; I was waiting a bit in case you find something else.
