### ISSUE TITLE
Using and DoFinally not called on cancel

### ISSUE THREAD

**Issue by Lukazoid** [akarnokd/Reactive4.NET#30]
Given the following example:

    var res = await Flowable.Using(() => new object(),
    i => Flowable.Interval(TimeSpan.FromSeconds(0.1)),
    r => Console.WriteLine("cleaning up"))
    .DoFinally(() => Console.WriteLine("on finally"))
    .Take(5)
    .ToList()
    .LastTask(CancellationToken.None);
    
Neither "cleaning up" or "on finally" ever get output. The `DoFinally` method even states that it will be invoked in cases of downstream cancellation.

**Comment by Lukazoid** [comment]
If I understand the reactive streams specification correctly, the issue is that after being cancelled, the upstream doesn't call anything to signal that it has completed cancellation, so the downstream is unable to do something in response to this (e.g. clear up resources).

Do you have any suggestion how this could be done safely, for the above example guaranteeing that the "cleaning up" or "on finally" is always output (after the inner publisher terminates), in cases of completion, error and cancellation?

I'm currently having an issue where some files are being left locked due to this.

**Comment by akarnokd** [comment]
It's an oversight. I fixed them in 0.2.18 just released.

Note, however, that I could not test it because VS and NUnit adapter refuse to run any tests for me.

**Comment by Lukazoid** [comment]
I think I know the solution of that, the test project needs to reference https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/ to expose it as a valid test project to VS.

The other test packages may also need updating.

**Comment by akarnokd** [comment]
Thanks, that worked.

**Comment by Lukazoid** [comment]
This seems to be working, thanks!
