### ISSUE TITLE
ConcatMap + ConcatWith delays error

### ISSUE THREAD

**Issue by zhuker** [akarnokd/Reactive4.NET#36]
RxJava 3
```
@Test
fun howConcatWithWorks() {
    Flowable.range(0, 5).concatMap { x ->
        println("x $x")
        if (x != 2)
            Flowable.just(x)
        else
            Flowable.just(x).concatWith(Flowable.error(Exception("wtf")));
    }
        .doOnNext { x -> println("ok $x") }
        .doOnError { err -> println("err ${err.message}") }
        .subscribe(
            { ok -> println("sub ok $ok") },
            { err -> println("sub err ${err.message}") });
}
```
output:
```
x 0
ok 0
sub ok 0
x 1
ok 1
sub ok 1
x 2
ok 2
sub ok 2
err wtf
sub err wtf
```

Reactive4.NET 0.2.18
```
[Test]
public void HowConcatWithWorks()
{
    Flowable.Range(0, 5).ConcatMap(x =>
        {
            Console.WriteLine($"x {x}");
            return x != 2
                ? Flowable.Just(x)
                : Flowable.Just(x).ConcatWith(Flowable.Error<int>(new Exception("wtf")));
        })
        .DoOnNext(x => Console.WriteLine($"ok {x}"))
        .DoOnError(err => Console.WriteLine($"err {err.Message}"))
        .Subscribe(ok => { Console.WriteLine($"sub ok {ok}"); },
            err => Console.WriteLine($"sub err {err.Message}"));
}
```   

output
```
x 0
ok 0
sub ok 0
x 1
ok 1
sub ok 1
x 2
ok 2
sub ok 2
x 3
ok 3
sub ok 3
x 4
ok 4
sub ok 4
err wtf
sub err wtf
```

**Comment by zhuker** [comment]
same thing happens without `ConcatWith` looks like `ConcatMap` delays errors

**Comment by akarnokd** [comment]
Yes, by design. You can work around it by using `FlatMap` with maximum concurrency of 1 and no error delay.

**Comment by zhuker** [comment]
what is the reasoning behind the design? do you know why rxjava3 chose not to delay errors?

**Comment by akarnokd** [comment]
Experience gained from RxJava. Most questions were about how to avoid eager errors with `concatMap` so I made it default here. RxJava, way back, started out as being eager by default and later has been extended with non-eager options.

**Comment by zhuker** [comment]
haha ok, i got so used to rxjava behavior (forced to use c# now)
would you consider adding `bool delayErrors` to `ConcatMap` which defaults to `true`?

**Comment by akarnokd** [comment]
Okay, I'll add the missing error modes shortly.

**Comment by akarnokd** [comment]
Done and published in v0.2.19.

Please let me now if it works for you.

**Comment by zhuker** [comment]
Works! Thanks!

```
    /// <summary>Report error after an inner source terminated.</summary>
    Boundary,
```
@akarnokd can you help me understand the difference between `Immediate` and `Boundary` 

i was under impression that inner source terminates as soon as error is produced

**Comment by akarnokd** [comment]
The main source could fail while the inner is still producing elements. Boundary will make the operator wait for the inner to finish before posting the error.
