### ISSUE TITLE
Flowable.Create with Buffer can deadlock

### ISSUE THREAD

**Issue by Lukazoid** [akarnokd/Reactive4.NET#4]
I would expect the following to complete in ~3 seconds however it appears to deadlock:

    var maxConcurrency = 2;
    var prefetch = Flowable.BufferSize();
    var backpressureStrategy = BackpressureStrategy.BUFFER;
    
    var flowable = Flowable.Range(0, 5).FlatMap(x =>
    {               
        return Flowable.Create<int>(e =>
        {
            // Thread to emulate some asynchronous action
            new Thread(() =>
            {
                for (var i = 0; i < 10; ++i)
                {
                    Thread.Sleep(100);

                    e.OnNext(x * i);
                }
                e.OnComplete();
            }).Start();
        }, backpressureStrategy);
    }, maxConcurrency, prefetch);

    var res = await flowable.ToList().FirstTask(CancellationToken.None).ConfigureAwait(false);

This deadlocks with both `FlatMap` and `ConcatMapEager`.

Changing any of the following avoids the deadlock:

1. maxConcurrency to 1
2. prefetch to 1
3. backpressureStrategy to anything other than BUFFER

I believe this could be bug with the fusion interaction between `FlatMap`/`ConcatMapEager` and `Flowable.Create`. I took a look in the code but I don't yet understand the fusion stuff properly to be of much help.

**Comment by akarnokd** [comment]
I'll check this out. If you suspect bugs due to optimizations, use `Hide()` to break them to see if the bug persists.

**Comment by Lukazoid** [comment]
Using `Hide()` on the `Flowable.Create` result does appear to avoid this deadlock.

**Comment by akarnokd** [comment]
Yes, this is a bug with the fused signalling of available data: `d && empty` may never execute if the previous round didn't empty the queue yet the done flag is set. I'll post a fix shortly.

**Comment by akarnokd** [comment]
Fixed via https://github.com/akarnokd/Reactive4.NET/commit/3592a37719f82c9cd19172835b74b4a1b176b70a which includes other operators having the same wrong pattern.
