### ISSUE TITLE
Task ToFlowable Deadlock When OperationCanceledException Thrown

### ISSUE THREAD

**Issue by Lukazoid** [akarnokd/Reactive4.NET#42]
The following results in a deadlock:

```csharp
async Task Main()
{
	var flowable = DelayThrowOperationCanceledException().ToFlowable();
	
	var result = await flowable.FirstTask(CancellationToken.None);
}

async Task<int> DelayThrowOperationCanceledException()
{
	await Task.Yield();
	throw new OperationCanceledException();
}
```

I believe this is because `OperationCanceledException` flags `Task.IsCanceled` instead of `Task.IsFaulted` which is not handled in `FlowableFromTask<T>.FromTaskSubscription.Run`.

**Comment by akarnokd** [comment]
Thanks for the report. I'll look into it as soon as I rectify VS opening such old .NET project properly.

**Comment by Lukazoid** [comment]
Thanks, I am working on a PR currently, however it looks like there's no way to get the original exception out of a canceled Task object so may be forced to just create a new exception to pass to `Error` which is not ideal but better than deadlocking I feel

**Comment by akarnokd** [comment]
Yep, fixed it like that. Will release it to NuGet shortly.

**Comment by Lukazoid** [comment]
Excellent, will this also fix the non-generic Task version?

**Comment by akarnokd** [comment]
Done. https://github.com/akarnokd/Reactive4.NET/releases/tag/v0.2.22

Please let me know if it works for you.

**Comment by akarnokd** [comment]
Oh, forgot about that.

**Comment by akarnokd** [comment]
Fixed that too. https://github.com/akarnokd/Reactive4.NET/releases/tag/v0.2.23

**Comment by Lukazoid** [comment]
Brilliant, thanks once again.

**Comment by Lukazoid** [comment]
@akarnokd I think I've found a way to obtain the original OperationCanceledException, this should allow the original exception details (message, stacktrace etc) to be retained:

```
if (task.IsCanceled)
{
    // obtain the originating cancellation exception
    try
    {
        task.GetAwaiter().GetResult();
    }
    catch (Exception ex)
    {
        Error(ex);
    }
}
```

Would it be possible to get this integrated?

**Comment by akarnokd** [comment]
Yep, that seems to work. Will post the next version shortly.

**Comment by akarnokd** [comment]
Done in 0.2.24
