### ISSUE TITLE
Fusion bug when using GroupBy and Publish

### ISSUE THREAD

**Issue by Lukazoid** [akarnokd/Reactive4.NET#5]
When using version 0.28 the following code throws an `ArgumentNullException`:

    var published = Flowable.FromArray("A", "AB", "BC")
        .GroupBy(x => x.Length)
        .Publish();

    published.Subscribe(g =>
    {
        Console.WriteLine(g.Key);
    });
    
    published.Connect();

The exception is:

> System.ArgumentNullException: Value cannot be null.
>  Parameter name: element
>    at Reactive4.NET.PublishProcessor\`1.OnNext(T element)
>    at Reactive4.NET.operators.FlowableGroupBy\`3.GroupBySubscriber.DrainFused()
>    at Reactive4.NET.operators.FlowableGroupBy\`3.GroupBySubscriber.OnNext(T element)
>    at Reactive4.NET.operators.FlowableArray\`1.ArraySubscription.Request(Int64 n)
>    at Reactive4.NET.operators.FlowableGroupBy\`3.GroupBySubscriber.OnSubscribe(ISubscription subscription)
>    at Reactive4.NET.operators.ConnectableFlowableMulticast\`1.Connect(Action\`1 onConnect)
>    at UserQuery.Main() in C:\Users\Luke\AppData\Local\Temp\LINQPad5\_zbuzgeyk\query_xpcuds.cs:line 46

Using `.Hide()` after the `GroupBy` and before `Publish` solves this.

**Comment by akarnokd** [comment]
Thanks, there is a missing fusion mode check in the PublishProcessor.onNext code. I'll post a fix shortly. Do you want a release as well?

**Comment by akarnokd** [comment]
Closing via https://github.com/akarnokd/Reactive4.NET/commit/e79046239b36751bb02e4050e35eb67648648237

**Comment by Lukazoid** [comment]
I am fine without a release, it was just something I tried and observed.

**Comment by akarnokd** [comment]
Already released 0.2.9. Thanks for testing the library.
