### ISSUE TITLE
Deadlock when using FlatMapEnumerable and SubscribeOn

### ISSUE THREAD

**Issue by Lukazoid** [akarnokd/Reactive4.NET#6]
The following examples never complete:

    await Flowable.Range(0, Flowable.BufferSize()+1)
        .SubscribeOn(Executors.Computation, true)
        .FlatMapEnumerable(x => new[] { x, x + 1, x + 2 })
        .LastTask(CancellationToken.None);

    await Flowable.Interval(TimeSpan.FromMilliseconds(20))
        .Take(Flowable.BufferSize()+1)
        .SubscribeOn(Executors.Computation, true)       
        .Map(x => x * 2)
        .FlatMapEnumerable(x => new[] { x, x + 1, x + 2})
        .LastTask(CancellationToken.None);

This does not deadlock when the source publisher publishes `Flowable.BufferSize()` items or less.

The common theme seems to be a source longer than `Flowable.BufferSize()` a `SubscribeOn` and a `FlatMapEnumerable`, it doesn't seem to matter what executor I use.

Replacing ` .FlatMapEnumerable(x => new[] { x, x + 1, x + 2})` with `.FlatMap(x => Flowable.FromEnumerable(new[] { x, x + 1, x + 2}))` does not deadlock, this implies to me the issue is with the `FlatMapEnumerable` internals.

**Comment by akarnokd** [comment]
Does it hang without `SubscribeOn`, or `SubscribeOn` with false?

**Comment by Lukazoid** [comment]
It doesn't hang without `SubscribeOn` but it does still hang when `requestOn` is `false`

**Comment by akarnokd** [comment]
Thanks, it is a bug in FlatMapEnumerable indeed. I forgot to keep requesting more. I'll fix it shortly.

**Comment by akarnokd** [comment]
Fixed in [v0.2.10](https://github.com/akarnokd/Reactive4.NET/releases/tag/v0.2.10).
