### ISSUE TITLE
Parallel + Sequential + Blocking Enumerable Deadlock

### ISSUE THREAD

**Issue by Lukazoid** [akarnokd/Reactive4.NET#7]
I discovered this while investigating another deadlock, possibly caused by the same underlying issue.

The following example deadlocks (`i` stops being incremented):

    var data = Flowable.Just(1).Repeat()
        .Parallel(1)
        .Sequential()
        .BlockingEnumerable();

    var i = 0;

    // A task to dump the progress
    Task.Run(() =>
    {
        while (true)
        {
            Thread.Sleep(1000);
            Console.WriteLine(i);
        }
    });

    foreach (var _ in data)
    {
        i++;
    }

**Comment by akarnokd** [comment]
Thanks. I'll investigate.

**Comment by Lukazoid** [comment]
Thanks @akarnokd, I believe it's most likely to do with the `Parallel` + `Sequential` as this is what the other deadlock I am investigating also has in common. 

I also observed if I change `ParallelFlowableTest.Sync()` to increment `j` up to 1000 the test fails:

> Different value count; Expected = 193, Actual = 97 (latch = 0, values = 97, errors = 0, completions = 1, subscribed = True, cancelled = False, tag = len=193, i=1)

**Comment by akarnokd** [comment]
There is an overrequest bug in a sync-fused parallel() operator's drain method. I'll post a fix shortly.

**Comment by akarnokd** [comment]
Closing via https://github.com/akarnokd/Reactive4.NET/releases/tag/v0.2.11
