### ISSUE TITLE
FlatMapEnumerable losing items

### ISSUE THREAD

**Issue by Lukazoid** [akarnokd/Reactive4.NET#8]
The following test case of `FlatMapEnumerable` fails:

    var n = 1000;
    Flowable.Range(0, n)
        .FlatMapEnumerable(x => new[] { x })
        .Test()
        .AssertValueCount(n);

The failure is:

> Different value count; Expected = 1000, Actual = 520 (latch = 0, values = 520, errors = 0, completions = 1, subscribed = True, cancelled = False)

This doesn't fail if I put `.Hide()` between the `Flowable.Range` and `FlatMapEnumerable` so it may be an issue with the fusion logic.

**Comment by akarnokd** [comment]
Thanks. Closing via [v0.2.12](https://github.com/akarnokd/Reactive4.NET/releases/tag/v0.2.12).
