### ISSUE TITLE
DoOnRequest fusion interaction

### ISSUE THREAD

**Issue by Lukazoid** [akarnokd/Reactive4.NET#9]
I'm unsure whether this is a bug or intentional but when using `DoOnRequest` with a sync fuseable subscriber the `DoOnRequest` callback never gets invoked, presumably because `Request` is never actually called. However I can also foresee that if a user has specified a `DoOnRequest` callback it's because the user wants to know when the downstream is ready to accept more data, perhaps `DoOnRequest` should not be fuseable?

What are your thoughts on this?

**Comment by akarnokd** [comment]
DoOnRequest has the BARRIER fusion marker, so it depends on what is driving it.

**Comment by Lukazoid** [comment]
So is it expected that in some cases the callback will never be called?

**Comment by akarnokd** [comment]
Yes, synchronously fused sequences.

**Comment by Lukazoid** [comment]
Ok thanks, that makes sense.
